# Mergify Rules
# 1. Automatic merge for RFC
# 2. Automatic merge for tooling
# 3. Remove stale reviews
# 4. Dependabot

pull_request_rules:

  # 1. Automatically merge master for RFC
  - name: automatic merge and squash for RFC
    actions:
      comment:
        message: Thanks for contributing! Your pull request will be updated from master and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
      delete_head_branch: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(work-in-progress|do-not-merge|tooling)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=2"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
  
  # 2. Automatically merge master for tooling
  - name: automatic merge and squash for tooling
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from master and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        # Merge instead of squash
        method: squash
        strict_method: merge
        commit_message: title+body
      delete_head_branch: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(work-in-progress|do-not-merge)
      - label~=(tooling)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
  
  # 3. Dismiss reviews that are stale/merged
  - name: remove stale reviews
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: true
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - base=master
      - -merged
      - -closed
  
  # 4. Automatically merge dependabot's blessed PRs
  - name: automatically merge Dependabot PRs
    actions:
      comment:
        message: Thanks Dependabot ðŸ™!
      merge:
        # 'strict: false' disables Mergify keeping the branch up-to-date from master.
        # It's not necessary: Dependabot will do that itself.
        # It's not dangerous: GitHub branch protection settings prevent merging stale branches.
        strict: false
        method: squash
      delete_head_branch: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(work-in-progress|do-not-merge)
      - -merged
      - -closed
      - author~=dependabot
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
